"""Adversarial transform for TraderBench: When Does Order Flow Matter? State-Dependent L2 Liquidity-State Transitions in Crypto Futures
Generated by capability-distiller from arxiv

Tests capability: regime_detection
"""
import random
from typing import List, Optional


def transform(bars: List[dict], config: Optional[dict] = None) -> List[dict]:
    """Apply regime_detection adversarial transform to bars.

    Tests the agent's ability to handle regime detection scenarios. Based on: Building event-conditioned market models requires separating macro-event labels from persistent microstructure state. We study
    """
    result = [dict(bar) for bar in bars]
    config = config or {}

    # # Adversarial logic for regime_detection:
#   Building event-conditioned market models requires separating macro-event labels from persistent microstructure state. We
    intensity = config.get("intensity", 0.1)
    seed = config.get("seed", 42)
    rng = random.Random(seed)

    for i, bar in enumerate(result):
        if rng.random() < intensity:
            # Inject adversarial pattern
            bar["close"] = bar["close"] * (1.0 + rng.uniform(-0.02, 0.02))
            bar["high"] = max(bar["high"], bar["close"] * 1.01)
            bar["low"] = min(bar["low"], bar["close"] * 0.99)

    return result
