"""Adversarial transform for TraderBench: The Science and Practice of Trend-Following Systems
Generated by capability-distiller from arxiv

Tests capability: trade_signal
"""
import random
from typing import List, Optional


def transform(bars: List[dict], config: Optional[dict] = None) -> List[dict]:
    """Apply trade_signal adversarial transform to bars.

    Tests the agent's ability to handle trade signal scenarios. Based on: We present a unified approach to designing trend-following (TF) systems and classify them into European, American, and Time Series
    """
    result = [dict(bar) for bar in bars]
    config = config or {}

    # # Adversarial logic for trade_signal:
#   We present a unified approach to designing trend-following (TF) systems and classify them into European, American, and T
    intensity = config.get("intensity", 0.1)
    seed = config.get("seed", 42)
    rng = random.Random(seed)

    for i, bar in enumerate(result):
        if rng.random() < intensity:
            # Inject adversarial pattern
            bar["close"] = bar["close"] * (1.0 + rng.uniform(-0.02, 0.02))
            bar["high"] = max(bar["high"], bar["close"] * 1.01)
            bar["low"] = min(bar["low"], bar["close"] * 0.99)

    return result
