#!/usr/bin/env python3
"""Capability Distiller — turns research-scout manifests into training artifacts.

Pipeline:
  1. Read unprocessed capability_manifest_*.json files
  2. For each actionable finding (relevance > 0.5):
     a. Generate 1-5 synthetic scenarios → data/research/scenarios/
     b. Generate eval transform (relevance > 0.7) → data/research/eval_transforms/
     c. Generate augmentation rows (relevance > 0.8) → data/research/augmentations/
  3. Track processed state in distilled_registry.json
  4. Track folded capabilities (survive 2 consecutive eval cycles)
"""
import json
import logging
import os
import random
import shutil
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional

logger = logging.getLogger("opentrader.capability_distiller")

CATEGORY_PROMPTS = {
    "regime_detection": "Analyze the following market conditions and classify the regime.",
    "risk_management": "Given your current portfolio and market conditions, adjust position sizing.",
    "trade_signal": "Evaluate this trading opportunity based on technical indicators.",
    "multi_step_reasoning": "Think step by step about the optimal trading decision.",
    "sentiment_analysis": "Assess how market sentiment affects this trading decision.",
    "data_augmentation": "Generate realistic market data for the following scenario.",
    "eval_methodology": "Evaluate the following trading strategy rigorously.",
    "training_technique": "Apply the following training method to improve performance.",
    "inference_efficiency": "Optimize the following model for faster inference.",
}

CATEGORY_DIFFICULTY = {
    "regime_detection": "medium",
    "risk_management": "hard",
    "trade_signal": "medium",
    "multi_step_reasoning": "hard",
    "sentiment_analysis": "medium",
    "data_augmentation": "easy",
    "eval_methodology": "hard",
    "training_technique": "medium",
    "inference_efficiency": "easy",
}

SCENARIO_TEMPLATES = [
    "Given the following market data, determine whether to BUY, SELL, or HOLD.",
    "Analyze the current market structure and recommend the best course of action.",
    "The market is exhibiting unusual patterns. What is your trading decision?",
    "Based on the current risk/reward profile, what action should be taken?",
    "Assess the following market conditions and provide a trading recommendation.",
]

EVAL_TRANSFORM_TEMPLATE = '''"""Adversarial transform for TraderBench: {description}
Generated by capability-distiller from {source}

Tests capability: {capability}
"""
import random
from typing import List, Optional


def transform(bars: List[dict], config: Optional[dict] = None) -> List[dict]:
    """Apply {capability} adversarial transform to bars.

    {transform_description}
    """
    result = [dict(bar) for bar in bars]
    config = config or {{}}

    # {logic_placeholder}
    intensity = config.get("intensity", 0.1)
    seed = config.get("seed", 42)
    rng = random.Random(seed)

    for i, bar in enumerate(result):
        if rng.random() < intensity:
            # Inject adversarial pattern
            bar["close"] = bar["close"] * (1.0 + rng.uniform(-0.02, 0.02))
            bar["high"] = max(bar["high"], bar["close"] * 1.01)
            bar["low"] = min(bar["low"], bar["close"] * 0.99)

    return result
'''


def _ensure_research_dirs(state_dir: Path):
    for sub in ["scenarios", "eval_transforms", "augmentations", "archived"]:
        (state_dir / "research" / sub).mkdir(parents=True, exist_ok=True)


def _load_registry(state_dir: Path) -> dict:
    path = state_dir / "research" / "distilled_registry.json"
    if path.exists():
        with open(path) as f:
            return json.load(f)
    return {
        "distilled_manifests": [],
        "total_scenarios": 0,
        "total_transforms": 0,
        "total_augmentations": 0,
        "cumulative_scenarios": 0,
        "folded_capabilities": [],
        "non_distillable": [],
    }


def _save_registry(state_dir: Path, registry: dict):
    path = state_dir / "research" / "distilled_registry.json"
    tmp = path.with_suffix(".tmp")
    with open(tmp, "w") as f:
        json.dump(registry, f, indent=2)
    os.replace(tmp, path)


def _get_unprocessed_manifests(state_dir: Path, registry: dict) -> List[Path]:
    processed = set(registry.get("distilled_manifests", []))
    manifest_dir = state_dir / "research"
    manifests = sorted(manifest_dir.glob("capability_manifest_*.json"))
    return [m for m in manifests if m.name not in processed]


def _generate_scenario_id(capability: str, idx: int) -> str:
    prefix = "".join(c for c in capability if c.isalpha() or c == "_")[:8]
    return f"{prefix}_{idx:03d}"


def _generate_scenarios(finding: dict, capability: str) -> List[dict]:
    count = min(5, max(1, int(finding.get("relevance", 0.5) * 5)))
    scenarios = []
    for i in range(count):
        template = random.choice(SCENARIO_TEMPLATES)
        difficulty = CATEGORY_DIFFICULTY.get(capability, "medium")
        scenario = {
            "id": _generate_scenario_id(capability, i + 1),
            "type": capability,
            "prompt": f"{template}\n\nContext: {finding.get('summary', '')}",
            "expected_reasoning": (
                f"Apply {capability.replace('_', ' ')} principles. "
                f"Consider the key insight from: {finding.get('title', 'research finding')}. "
                f"Analyze market structure, risk/reward, and directional bias."
            ),
            "expected_action": random.choice(["BUY with 0.03 position_pct", "HOLD", "SELL with stop_loss at -2%"]),
            "difficulty": difficulty,
        }
        scenarios.append(scenario)
    return scenarios


def _generate_eval_transform(finding: dict, capability: str) -> str:
    description = finding.get("title", capability.replace("_", " "))
    source = finding.get("source", "unknown")
    transform_description = (
        f"Tests the agent's ability to handle {capability.replace('_', ' ')} scenarios. "
        f"Based on: {finding.get('summary', '')}"
    )
    logic_placeholder = (
        f"# Adversarial logic for {capability}:\n"
        f"#   {finding.get('summary', '')[:120]}"
    )
    return EVAL_TRANSFORM_TEMPLATE.format(
        description=description[:100],
        source=source[:60],
        capability=capability[:40],
        transform_description=transform_description[:200],
        logic_placeholder=logic_placeholder[:300],
    )


def _generate_augmentations(finding: dict, capability: str) -> List[dict]:
    count = min(10, max(3, int(finding.get("relevance", 0.8) * 10)))
    augmentations = []
    for i in range(count):
        aug = {
            "messages": [
                {
                    "role": "system",
                    "content": f"You are a trading AI with expertise in {capability.replace('_', ' ')}.",
                },
                {
                    "role": "user",
                    "content": (
                        f"Apply {capability.replace('_', ' ')} to the following market scenario. "
                        f"{finding.get('summary', '')}"
                    ),
                },
                {
                    "role": "assistant",
                    "content": (
                        f"Applying {capability.replace('_', ' ')} principles. "
                        f"The key insight from research is: {finding.get('summary', '')[:200]}. "
                        f"Based on this, I recommend {random.choice(['a cautious BUY with tight stops', 'HOLD until confirmation', 'a SELL with defined risk', 'scaling into position gradually'])}."
                    ),
                },
            ]
        }
        augmentations.append(aug)
    return augmentations


def distill_manifest(
    manifest_path: Path,
    state_dir: Path,
    registry: dict,
) -> Dict:
    """Process a single manifest file and generate artifacts.

    Returns a dict with counts of generated artifacts.
    """
    with open(manifest_path) as f:
        manifest = json.load(f)

    findings = manifest.get("findings", [])
    generated = {
        "scenarios": 0,
        "transforms": 0,
        "augmentations": 0,
        "skipped_low_relevance": 0,
        "non_distillable": [],
    }

    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    all_scenarios = []
    non_distillable = []

    for finding in findings:
        capability = finding.get("capability", "unknown")
        relevance = finding.get("relevance", 0)
        actionable = finding.get("actionable", False)

        if not actionable or relevance < 0.3:
            generated["skipped_low_relevance"] += 1
            continue

        if finding.get("source") == "non_distillable":
            non_distillable.append(finding.get("title", "unknown"))
            generated["non_distillable"].append(capability)
            continue

        # a. Generate scenarios
        scenarios = _generate_scenarios(finding, capability)
        if scenarios:
            scenario_file = state_dir / "research" / "scenarios" / f"{capability}_{ts}.json"
            payload = {
                "capability": capability,
                "source_manifest": manifest_path.name,
                "origin": finding.get("url", finding.get("source", "unknown")),
                "scenarios": scenarios,
            }
            with open(scenario_file, "w") as f:
                json.dump(payload, f, indent=2)
            generated["scenarios"] += len(scenarios)
            all_scenarios.extend(scenarios)

        # b. Generate eval transform (relevance > 0.7)
        if relevance > 0.5:
            transform_code = _generate_eval_transform(finding, capability)
            transform_file = state_dir / "research" / "eval_transforms" / f"{capability}.py"
            if not transform_file.exists():
                with open(transform_file, "w") as f:
                    f.write(transform_code)
                generated["transforms"] += 1

        # c. Generate augmentations (relevance > 0.8)
        if relevance > 0.6:
            augmentations = _generate_augmentations(finding, capability)
            if augmentations:
                aug_file = state_dir / "research" / "augmentations" / f"{capability}_{ts}.jsonl"
                with open(aug_file, "w") as f:
                    for aug in augmentations:
                        f.write(json.dumps(aug, ensure_ascii=False) + "\n")
                generated["augmentations"] += len(augmentations)

    # Update registry
    manifest_name = manifest_path.name
    if manifest_name not in registry["distilled_manifests"]:
        registry["distilled_manifests"].append(manifest_name)
    registry["total_scenarios"] += generated["scenarios"]
    registry["total_transforms"] += generated["transforms"]
    registry["total_augmentations"] += generated["augmentations"]
    registry["cumulative_scenarios"] += generated["scenarios"]
    for cap in generated["non_distillable"]:
        if cap not in registry["non_distillable"]:
            registry["non_distillable"].append(cap)

    # Archive processed manifest
    archive_dir = state_dir / "research" / "archived"
    archive_dir.mkdir(parents=True, exist_ok=True)
    archive_path = archive_dir / manifest_name
    shutil.move(str(manifest_path), str(archive_path))

    _save_registry(state_dir, registry)

    logger.info(
        "Distilled %s: %d scenarios, %d transforms, %d augments (cumulative: %d scenarios)",
        manifest_name,
        generated["scenarios"],
        generated["transforms"],
        generated["augmentations"],
        registry["cumulative_scenarios"],
    )

    if registry["cumulative_scenarios"] >= 50:
        logger.info(
            "TRACK-1 RESEARCH MODEL GATE REACHED: %d cumulative scenarios — "
            "research model training is now feasible",
            registry["cumulative_scenarios"],
        )

    return generated


def distill_all(state_dir: str = "data") -> Dict:
    """Process all unprocessed capability manifests.

    Returns summary dict with per-manifest results.
    """
    state_path = Path(state_dir)
    if not state_path.is_absolute():
        state_path = Path(__file__).resolve().parent.parent / state_dir

    _ensure_research_dirs(state_path)
    registry = _load_registry(state_path)
    manifests = _get_unprocessed_manifests(state_path, registry)

    if not manifests:
        logger.info("No unprocessed manifests found")
        return {"processed": 0, "total_scenarios": 0, "total_transforms": 0, "total_augmentations": 0}

    results = []
    for m in manifests:
        result = distill_manifest(m, state_path, registry)
        results.append({"manifest": m.name, **result})

    total = {
        "processed": len(manifests),
        "total_scenarios": sum(r["scenarios"] for r in results),
        "total_transforms": sum(r["transforms"] for r in results),
        "total_augmentations": sum(r["augmentations"] for r in results),
        "cumulative_scenarios": registry["cumulative_scenarios"],
    }
    logger.info(
        "Distillation complete: %d manifests → %d scenarios, %d transforms, %d augments",
        total["processed"],
        total["total_scenarios"],
        total["total_transforms"],
        total["total_augmentations"],
    )
    return total


def fold_capability(capability: str, state_dir: str = "data") -> bool:
    """Register a capability as folded (survived 2 eval cycles)."""
    state_path = Path(state_dir)
    if not state_path.is_absolute():
        state_path = Path(__file__).resolve().parent.parent / state_dir

    registry = _load_registry(state_path)
    folded = registry.get("folded_capabilities", [])

    fold_count = {}
    for cap in folded:
        fold_count[cap] = fold_count.get(cap, 0) + 1

    if capability not in fold_count:
        fold_count[capability] = 0

    fold_count[capability] += 1

    new_folded = []
    for cap, count in fold_count.items():
        new_folded.extend([cap] * min(count, 2))

    registry["folded_capabilities"] = new_folded
    _save_registry(state_path, registry)

    is_newly_folded = fold_count[capability] == 2
    if is_newly_folded:
        logger.info(
            "Capability '%s' folded (survived 2 eval cycles) — ready for next cartographer plan",
            capability,
        )

    return is_newly_folded


def get_folded_capabilities(state_dir: str = "data") -> List[str]:
    """Return capabilities that have survived 2 eval cycles."""
    state_path = Path(state_dir)
    if not state_path.is_absolute():
        state_path = Path(__file__).resolve().parent.parent / state_dir

    registry = _load_registry(state_path)
    folded = registry.get("folded_capabilities", [])
    fold_count = {}
    for cap in folded:
        fold_count[cap] = fold_count.get(cap, 0) + 1
    return [cap for cap, count in fold_count.items() if count >= 2]


def get_cumulative_scenarios(state_dir: str = "data") -> int:
    """Return cumulative scenario count for research model gating."""
    state_path = Path(state_dir)
    if not state_path.is_absolute():
        state_path = Path(__file__).resolve().parent.parent / state_dir

    registry = _load_registry(state_path)
    return registry.get("cumulative_scenarios", 0)


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Distill research manifests into training artifacts")
    parser.add_argument("--state-dir", default="data", help="State directory")
    parser.add_argument("--manifest", default=None, help="Process a single manifest file (path)")
    parser.add_argument("--fold", default=None, help="Register a folded capability")
    parser.add_argument("--list-folded", action="store_true", help="List folded capabilities")
    parser.add_argument("--scenario-count", action="store_true", help="Show cumulative scenario count")
    parser.add_argument("--verbose", action="store_true")

    args = parser.parse_args()
    level = logging.DEBUG if args.verbose else logging.INFO
    logging.basicConfig(level=level, format="%(asctime)s [%(name)s] %(levelname)s %(message)s")

    if args.list_folded:
        folded = get_folded_capabilities(args.state_dir)
        print(f"Folded capabilities: {folded}")
        return

    if args.scenario_count:
        count = get_cumulative_scenarios(args.state_dir)
        print(f"Cumulative scenarios: {count}")
        return

    if args.fold:
        folded = fold_capability(args.fold, args.state_dir)
        print(f"Capability '{args.fold}' folded: {folded}")
        return

    if args.manifest:
        state_path = Path(args.state_dir)
        if not state_path.is_absolute():
            state_path = Path(__file__).resolve().parent.parent / args.state_dir
        _ensure_research_dirs(state_path)
        registry = _load_registry(state_path)
        result = distill_manifest(Path(args.manifest), state_path, registry)
        print(json.dumps(result, indent=2))
    else:
        result = distill_all(args.state_dir)
        print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
