"""Adversarial transform for TraderBench: Reinforcement Learning for Execution under Dynamic Fees in a Closed-Loop DEX Simulator
Generated by capability-distiller from arxiv

Tests capability: multi_step_reasoning
"""
import random
from typing import List, Optional


def transform(bars: List[dict], config: Optional[dict] = None) -> List[dict]:
    """Apply multi_step_reasoning adversarial transform to bars.

    Tests the agent's ability to handle multi step reasoning scenarios. Based on: Trader-facing dynamic fees are increasingly proposed for automated market makers (AMMs), but historical data do not identi
    """
    result = [dict(bar) for bar in bars]
    config = config or {}

    # # Adversarial logic for multi_step_reasoning:
#   Trader-facing dynamic fees are increasingly proposed for automated market makers (AMMs), but historical data do not iden
    intensity = config.get("intensity", 0.1)
    seed = config.get("seed", 42)
    rng = random.Random(seed)

    for i, bar in enumerate(result):
        if rng.random() < intensity:
            # Inject adversarial pattern
            bar["close"] = bar["close"] * (1.0 + rng.uniform(-0.02, 0.02))
            bar["high"] = max(bar["high"], bar["close"] * 1.01)
            bar["low"] = min(bar["low"], bar["close"] * 0.99)

    return result
